const header=document.querySelector('.site-header'),nav=document.querySelector('.nav-links');
document.querySelectorAll('[data-menu]').forEach(b=>b.addEventListener('click',()=>nav?.classList.toggle('open')));
addEventListener('scroll',()=>header?.classList.toggle('scrolled',scrollY>26),{passive:true});
const page=location.pathname.split('/').pop()||'index.html';
document.querySelectorAll('.nav-links a').forEach(a=>{if(a.getAttribute('href')===page)a.classList.add('active');a.addEventListener('click',()=>nav?.classList.remove('open'));});
const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
if(window.gsap&&!reduce){gsap.registerPlugin(ScrollTrigger);gsap.set('.reveal,.mask-reveal',{autoAlpha:0,y:42});gsap.utils.toArray('.reveal,.mask-reveal').forEach(el=>gsap.to(el,{autoAlpha:1,y:0,duration:1.05,ease:'power3.out',scrollTrigger:{trigger:el,start:'top 82%'}}));gsap.utils.toArray('.mask-reveal img').forEach(img=>gsap.fromTo(img,{scale:1.12},{scale:1,duration:1.4,ease:'power3.out',scrollTrigger:{trigger:img,start:'top 85%'}}));gsap.utils.toArray('.hero-copy > *').forEach((el,i)=>gsap.from(el,{autoAlpha:0,y:38,duration:1.1,delay:.15+i*.12,ease:'power3.out'}));gsap.utils.toArray('.hero-media img').forEach(img=>gsap.to(img,{yPercent:8,ease:'none',scrollTrigger:{trigger:img.closest('section'),start:'top top',end:'bottom top',scrub:true}}));document.querySelectorAll('.horizontal-section').forEach(sec=>{const track=sec.querySelector('.h-track');if(track&&innerWidth>760){gsap.to(track,{x:()=>-(track.scrollWidth-innerWidth+innerWidth*.12),ease:'none',scrollTrigger:{trigger:sec,start:'top top',end:()=>'+='+(track.scrollWidth*.75),scrub:1,pin:true,anticipatePin:1}})}});gsap.utils.toArray('.pin-story').forEach(sec=>ScrollTrigger.create({trigger:sec.querySelector('.pin-copy'),start:'top 130px',endTrigger:sec,end:'bottom bottom',pin:innerWidth>980,pinSpacing:false}));}else{document.querySelectorAll('.reveal,.mask-reveal').forEach(el=>{el.style.opacity=1;el.style.transform='none';});}
document.querySelectorAll('.magnetic').forEach(el=>{el.addEventListener('mousemove',e=>{const r=el.getBoundingClientRect();el.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.08}px,${(e.clientY-r.top-r.height/2)*.08}px)`});el.addEventListener('mouseleave',()=>el.style.transform='');});
document.querySelectorAll('form[data-static-form]').forEach(f=>f.addEventListener('submit',e=>{e.preventDefault();const n=f.querySelector('.form-note');if(n)n.textContent='This static form is ready, but needs an enquiry endpoint before live submissions.';}));
const lb=document.createElement('div');lb.className='lightbox';lb.innerHTML='<button aria-label="Close">×</button><img alt=""><p></p>';document.body.appendChild(lb);const lbi=lb.querySelector('img'),cap=lb.querySelector('p');
document.querySelectorAll('.gallery-tile img,.strip-grid img').forEach(img=>img.addEventListener('click',()=>{lbi.src=img.currentSrc||img.src;lbi.alt=img.alt;cap.textContent=img.alt;lb.classList.add('open');}));
lb.addEventListener('click',e=>{if(e.target===lb||e.target.tagName==='BUTTON')lb.classList.remove('open')});addEventListener('keydown',e=>{if(e.key==='Escape')lb.classList.remove('open')});
